---
- hosts: all
  become: true
  tasks:

    - name: "update apt"
      apt:
        update_cache: yes

    - name: "instal apache 2"
      apt:
        name: apache2
        state: absent

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: absent


